site_name: NSI
site_description: "Support de cours"
copyright: "CC-BY-NC-SA 4.0"
docs_dir: docs

nav:
    - "Home": index.md    
    - "NSI1":
        - "Seq. 1": NSI1/S1/sequence1.md
        - "Seq.2": NSI1/S2/sequence2.md
        - "Seq.3":
            - "ACTIVITE 1": NSI1/S3/S3A1.md
            - "ACTIVITE 2": NSI1/S3/S3A2.md
            - "COURS 1": NSI1/S3/S3C1.md
            - "COURS 2": NSI1/S3/S3C2.md
            - "COURS 3": NSI1/S3/S3C3.md
            - "TP 1": NSI1/S3/TP1S3.md
            - "Annexe TP1": NSI1/S3/Annexe_TP.md
            - "EXERCICES E1": NSI1/S3/S3E1.md
            - "EXERCICES E2": NSI1/S3/doc/Exercices_codage_nombre.pdf
            - "En Résumé": NSI1/S3/S3R1.md
            
    - "NSITerm":
        - "Chap. 1 Récursivité":
            - "Cours": NSITerm/LP2/Recursivite.md
            - "Exercices": NSITerm/LP2/C1E1.md
        - "Chap. 2 Prog. modulaire":
            - "Actvité 1": NSITerm/LP2/C4A1.md
            - "Actvité 2": NSITerm/LP2/C4A2.md
        - "Chap. 3 Mise au point - Bugs":
            - "Cours": NSITerm/LP2/C5C1.md
            - "Exercices": NSITerm/LP2/C5E1.md
        - "Chap. 4 SDD1 Pile & File":
            - "Cours": NSITerm/SD/C2C1.md
            - "Exercices": NSITerm/SD/C2E1.md
        - "Chap. 5 Vocabulaire POO":
            - "Cours": NSITerm/SD/C3C1.md
            - "Exercices 1": NSITerm/SD/C3E1.md
            - "Exercices 2": NSITerm/SD/C3E2.md
        - "Chap. 6 SDD2 Liste":
            - "Cours": NSITerm/SD/C6C1.md
            - "Exercices": NSITerm/SD/C6E1.md

theme:
    name: material
    font: false                     # RGPD ; pas de fonte Google
    language: fr                    # français
    palette:                        # Palettes de couleurs jour/nuit
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: indigo
        accent: indigo
        toggle:
            icon: material/weather-sunny
            name: Passer au mode nuit
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: blue
        accent: blue
        toggle:
            icon: material/weather-night
            name: Passer au mode jour
    features:
        - navigation.instant
        - navigation.tabs
        - navigation.expand
        - navigation.top
        - toc.integrate
        - header.autohide


markdown_extensions:
    - meta
    - abbr

    - def_list                      # Les listes de définition.
    - attr_list                     # Un peu de CSS et des attributs HTML.
    - footnotes                     # Notes[^1] de bas de page.  [^1]: ma note.
    - admonition                    # Blocs colorés  !!! info "ma remarque"
    - pymdownx.details              #   qui peuvent se plier/déplier.
    - pymdownx.caret                # Passage ^^souligné^^ ou en ^exposant^.
    - pymdownx.mark                 # Passage ==surligné==.
    - pymdownx.tilde                # Passage ~~barré~~ ou en ~indice~.
    - pymdownx.highlight:           # Coloration syntaxique du code
        linenums: true
    - pymdownx.inlinehilite         # pour  `#!python  <python en ligne>`
    - pymdownx.snippets             # Inclusion de fichiers externe.
    - pymdownx.tasklist:            # Cases à cocher  - [ ]  et - [x]
        custom_checkbox:    false   #   avec cases d'origine
        clickable_checkbox: true    #   et cliquables.
    - pymdownx.tabbed               # Volets glissants.  === "Mon volet"
    - pymdownx.superfences          # Imbrication de blocs.
    - pymdownx.keys:                # Touches du clavier.  ++ctrl+d++
        separator: "\uff0b"
    - pymdownx.emoji:               # Émojis  :boom:
        emoji_index:     !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg


    - pymdownx.arithmatex:
        generic: true
    - toc:
        permalink: ⚓︎
        toc_depth: 2

plugins:
  - search
  - macros
  

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid@8.9.2/dist/mermaid.min.js
  - javascripts/mermaid.js

extra_css:
  - stylesheets/extra.css
